<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>GForceDisplay</AssemblyName>
    <RootNamespace>GForceDisplay</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <KspRoot Condition="'$(KspRoot)' == ''">$(KSP_ROOT)</KspRoot>
    <OutputPath>..\..\GameData\GForceDisplay\Plugins\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(KspRoot)\KSP_x64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(KspRoot)\KSP_x64_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(KspRoot)\KSP_x64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(KspRoot)\KSP_x64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ClickThroughBlocker">
      <HintPath>$(KspRoot)\GameData\000_ClickThroughBlocker\Plugins\ClickThroughBlocker.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ToolbarControl">
      <HintPath>$(KspRoot)\GameData\001_ToolbarControl\Plugins\ToolbarControl.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
